---
title: "BATS_dada2_2024seqs_Lane2"
author: "Nicole Dames"
date: "`r Sys.Date()`"
output: html_document
---

```{r knitr root.dir }
library(dada2)

rm(list=ls()) 
knitr::opts_knit$set(root.dir = "/Users/ndames/Library/CloudStorage/Dropbox/Postdoc/Worden_Postdoc_2024_2026/Archaea_LTT/V4_BIOSCOPE_Processcruise_2022-2024/extracted_files/LTT_J24_V4_L2-456577265")

#create vector that denotes path
path <- "/Users/ndames/Library/CloudStorage/Dropbox/Postdoc/Worden_Postdoc_2024_2026/Archaea_LTT/V4_BIOSCOPE_Processcruise_2022-2024/extracted_files/LTT_J24_V4_L2-456577265/Lane2_BATS_V4"
```

# Data import and filtering
```{r}
#sort our fastq files into forward (R1) and reverse (R2) reads 
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))

#pull out our sample names
sample.names <- sapply(strsplit(basename(fnFs), "_L"), `[`, 1)

#filter our samples
filt_path <- file.path(path, "filtered")
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq"))
```

# Read quality plots-forward
```{r}
#plot the QUALITY of our sequences
plotQualityProfile(fnFs[1:132])
```


# Read quality plots-reverse
```{r}
plotQualityProfile(fnRs[1:10])
```


#Trimming sequences: MaxEE=c(2,2)
```{r}
out_full <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(250,150),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,trimLeft=c(19,20),
              compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out_full)
```
#Rarefy reads: minimum number of reads: 10000 
```{r}
min_reads <- 10000

keep <- out_full[,2] >= min_reads

removed_samples <- rownames(out_full)[!keep]

removed_df <- data.frame(
  sample = rownames(out_full)[!keep],
  input_reads = out_full[!keep,1],
  filtered_reads = out_full[!keep,2]
)

write.csv(removed_df,
          "samples_removed_minReads_Lane2.csv",
          row.names = FALSE)
```

#Create filtered subset objects now
```{r}
fnFs_filt   <- fnFs[keep]
fnRs_filt   <- fnRs[keep]
filtFs_filt <- filtFs[keep]
filtRs_filt <- filtRs[keep]
sample.names_filt <- sample.names[keep]

out_filt <- out_full[keep,]

```

#dereplicate

```{r}
#dereplicate our sequences (pull out 1 copy of each sequence)
derepFs <- derepFastq(filtFs_filt, verbose=TRUE)
derepRs <- derepFastq(filtRs_filt, verbose=TRUE)

#use sample names with newly created dereplicated samples
names(derepFs) <- sample.names_filt
names(derepRs) <- sample.names_filt
```

#dada2_run_default
```{r}
#THESE NEXT LINES ARE WORKHORSE OF DADA2- 
#GET RID OF SEQUENCER ERROR TO PRODUCE EXACT DNA SEQUENCES (ASVs)
#calculates/learns error rates in these samples
dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist = TRUE, multithread=TRUE)
errF <- dadaFs.lrn[[1]]$err_out
dadaRs.lrn <- dada(derepRs, err=NULL, selfConsist = TRUE, multithread=TRUE)
errR <- dadaRs.lrn[[1]]$err_out

#save error files
saveRDS(errF, "errF.rds")
saveRDS(errR, "errR.rds")

#Denoise our samples with calculated error from previous step
dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE)

#save files
saveRDS(dadaFs, "dadaFs_N.rds")
saveRDS(dadaRs, "dadaRs_N.rds")
```

#Merge reads and remove chimeras - Lane 1
```{r}
#merge our forward and reverse reads into one long read
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
saveRDS(mergers, "dadaFs_N.rds")

#create table of DNA sequences in each sample
seqtab <- makeSequenceTable(mergers[names(mergers) != "Mock"])
#look at dimensions of this dataframe
dim(seqtab)
table(nchar(getSequences(seqtab)))

#Remove DNA chimeras from dataset
seqtab.nochim <- removeBimeraDenovo(seqtab, verbose=TRUE)
sum(seqtab.nochim)/sum(seqtab)
dim(seqtab.nochim)

#save our sequences in dataframe
saveRDS(seqtab.nochim, "dadaFs_Nseqtab.nochim.rds")
```


#Sanity check-Lane 1
```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(
  out_filt,
  denoisedF = sapply(dadaFs, getN),
  denoisedR = sapply(dadaRs, getN),
  merged = sapply(mergers, getN),
  nonchim = rowSums(seqtab.nochim)
  
)
head(track)
```

#Assign taxa to Lane 2_silva
```{r}
#assign taxonomy to DNA sequences usings SILVA reference database
taxa <- assignTaxonomy(seqtab.nochim, "/Users/ndames/Library/CloudStorage/Dropbox/Postdoc/Worden_Postdoc_2024_2026/Archaea_LTT/DADA2_Test/silva_nr99_v138.2_toSpecies_trainset.fa")

#look at most abundant taxonomy
unname(head(taxa))

#save taxa
saveRDS(taxa, "taxa.rds")

#write our abundance table
write.table(cbind(t(seqtab.nochim) , taxa), "Lane2_BATS_default_seqtab-nochimtaxa.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)

#write our taxa file
write.table(taxa,"Lane2_BATS_default_taxa.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)
```


#Assign taxa to Lane 2_GTDB
```{r}
#assign taxonomy to DNA sequences using GTDB reference database
taxa <- assignTaxonomy(seqtab.nochim, "/Users/ndames/Library/CloudStorage/Dropbox/Postdoc/Worden_Postdoc_2024_2026/Archaea_LTT/DADA2_Test/GTDB_bac120_arc122_ssu_r202_fullTaxo.fa")

#look at most abundant taxonomy
unname(head(taxa))

#save taxa
saveRDS(taxa, "taxa_gtdb.rds")

#write our abundance table
write.table(cbind(t(seqtab.nochim) , taxa), "Lane2_BATS_GTDB_seqtab-nochimtaxa.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)

#write our taxa file
write.table(taxa,"Lane2_BATS_GTDB_taxa.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)
```

